import { IUserInfo } from './IEmployee';

/**
 * Workflow Task entity representing a task within a JML process
 */
export interface IWorkflowTask {
  Id?: number;
  title: string;
  jmlProcessId: number;
  employeeId: number;
  taskCategory: TaskCategory;
  assignedTo: IUserInfo;
  status: TaskStatus;
  priority: TaskPriority;
  dueDate: Date;
  completedDate?: Date;
  taskType: string;
  dependsOn?: number; // Task ID
  estimatedHours?: number;
  actualHours?: number;
  completionNotes?: string;
  autoGenerated: boolean;
  reminderSent?: boolean;
  slaDeadline?: Date;
}

export enum TaskCategory {
  HR = "HR",
  IT = "IT",
  Facilities = "Facilities",
  Manager = "Manager",
  Employee = "Employee"
}

export enum TaskStatus {
  NotStarted = "Not Started",
  InProgress = "In Progress",
  Completed = "Completed",
  Blocked = "Blocked",
  Cancelled = "Cancelled"
}

export enum TaskPriority {
  Low = "Low",
  Medium = "Medium",
  High = "High",
  Critical = "Critical"
}
