import { PnPService } from './PnPService';
import { ErrorHandlerService } from './ErrorHandler';
import { IWorkflowTemplate, IWorkflowTaskTemplate, TaskAssignmentRule } from '../models/IWorkflowTemplate';
import { ProcessType } from '../models/IJMLProcess';
import { IJMLTask, TaskStatus } from '../models/IJMLTask';

/**
 * Service for managing workflow templates and generating tasks from templates
 */
export class WorkflowTemplateService {
  private pnpService: PnPService;

  constructor(pnpService: PnPService) {
    this.pnpService = pnpService;
  }

  /**
   * Get workflow template by process type and optional filters
   */
  public async getTemplateForProcess(
    processType: ProcessType,
    department?: string,
    employeeType?: string
  ): Promise<IWorkflowTemplate | null> {
    try {
      // Build filter criteria
      let filter = `ProcessType eq '${processType}' and IsActive eq true`;

      if (department) {
        filter += ` and (Department eq '${department}' or Department eq null)`;
      }

      if (employeeType) {
        filter += ` and (EmployeeType eq '${employeeType}' or EmployeeType eq null)`;
      }

      const templates = await this.pnpService.getListItems<any>(
        'Workflow Templates',
        undefined,
        filter,
        'Department desc, EmployeeType desc', // Prioritize specific over general templates
        1
      );

      if (templates.length === 0) {
        return null;
      }

      // Get task templates for this workflow
      const taskTemplates = await this.getTaskTemplates(templates[0].TemplateId);

      return this.mapToWorkflowTemplate(templates[0], taskTemplates);
    } catch (error) {
      ErrorHandlerService.handle(error as Error, 'WorkflowTemplateService.getTemplateForProcess');
      throw error;
    }
  }

  /**
   * Generate tasks from workflow template
   */
  public async generateTasksFromTemplate(
    templateId: string,
    processId: number,
    employeeId: number,
    processStartDate: Date,
    overrides?: {
      hrCoordinatorId?: number;
      itCoordinatorId?: number;
      managerId?: number;
      department?: string;
    }
  ): Promise<IJMLTask[]> {
    try {
      // Get the template
      const template = await this.getTemplateById(templateId);
      if (!template) {
        throw new Error(`Template not found: ${templateId}`);
      }

      // Generate tasks
      const tasks: any[] = [];

      for (const taskTemplate of template.tasks) {
        const dueDate = new Date(processStartDate);
        dueDate.setDate(dueDate.getDate() + taskTemplate.daysOffset);

        // Determine assignee based on assignment rule
        const assigneeId = await this.resolveAssignee(taskTemplate, overrides);

        const task = {
          Title: taskTemplate.title,
          JMLTaskDescription: taskTemplate.description,
          JMLProcessLookupId: processId,
          JMLTaskEmployeeLookupId: employeeId,
          JMLTaskCategory: taskTemplate.taskCategory,
          JMLTaskStatus: TaskStatus.NotStarted,
          JMLTaskPriority: taskTemplate.priority,
          JMLTaskDueDate: dueDate.toISOString(),
          JMLTaskSequence: taskTemplate.sequenceOrder,
          JMLTaskEstimatedHours: taskTemplate.estimatedHours,
          JMLTaskDependencies: taskTemplate.dependencies?.join(', '),
          JMLTaskAutoGenerated: true,
          JMLTaskTemplateSource: taskTemplate.taskTemplateId,
          JMLTaskAssignedToId: assigneeId,
          JMLTaskNotes: taskTemplate.instructions || ''
        };

        tasks.push(task);
      }

      // Batch create all tasks
      const createdTasks = await this.pnpService.batchCreateItems<any>('JML Tasks', tasks);

      return createdTasks.map(t => this.mapToJMLTask(t));
    } catch (error) {
      ErrorHandlerService.handle(error as Error, 'WorkflowTemplateService.generateTasksFromTemplate');
      throw error;
    }
  }

  /**
   * Create new workflow template
   */
  public async createTemplate(template: IWorkflowTemplate): Promise<number> {
    try {
      // Create main template
      const templateData = {
        Title: template.templateName,
        TemplateId: template.templateId,
        TemplateName: template.templateName,
        Description: template.description,
        ProcessType: template.processType,
        IsActive: template.isActive,
        Department: template.department,
        EmployeeType: template.employeeType,
        Priority: template.priority,
        EstimatedDurationDays: template.estimatedDurationDays
      };

      const result = await this.pnpService.createListItem<any>(
        'Workflow Templates',
        templateData
      );

      // Create task templates
      if (template.tasks && template.tasks.length > 0) {
        const taskTemplates = template.tasks.map(task => ({
          Title: task.title,
          TaskTemplateId: task.taskTemplateId,
          WorkflowTemplateId: template.templateId,
          TaskTitle: task.title,
          TaskDescription: task.description,
          TaskCategory: task.taskCategory,
          TaskPriority: task.priority,
          SequenceOrder: task.sequenceOrder,
          DaysOffset: task.daysOffset,
          EstimatedHours: task.estimatedHours,
          IsRequired: task.isRequired,
          Dependencies: task.dependencies?.join(', '),
          AssignmentRule: task.assignmentRule,
          AssigneeRole: task.assigneeRole,
          AssigneeEmail: task.assigneeEmail,
          RequiresApproval: task.requiresApproval,
          AutoComplete: task.autoComplete,
          NotifyOnAssignment: task.notifyOnAssignment,
          NotifyBeforeDueDays: task.notifyBeforeDueDays,
          Instructions: task.instructions
        }));

        await this.pnpService.batchCreateItems('Workflow Task Templates', taskTemplates);
      }

      return result.Id!;
    } catch (error) {
      ErrorHandlerService.handle(error as Error, 'WorkflowTemplateService.createTemplate');
      throw error;
    }
  }

  /**
   * Update workflow template
   */
  public async updateTemplate(templateId: number, updates: Partial<IWorkflowTemplate>): Promise<void> {
    try {
      const updateData: any = {};

      if (updates.templateName) updateData.TemplateName = updates.templateName;
      if (updates.description) updateData.Description = updates.description;
      if (updates.isActive !== undefined) updateData.IsActive = updates.isActive;
      if (updates.department) updateData.Department = updates.department;
      if (updates.employeeType) updateData.EmployeeType = updates.employeeType;
      if (updates.priority) updateData.Priority = updates.priority;
      if (updates.estimatedDurationDays) updateData.EstimatedDurationDays = updates.estimatedDurationDays;

      await this.pnpService.updateListItem('Workflow Templates', templateId, updateData);
    } catch (error) {
      ErrorHandlerService.handle(error as Error, 'WorkflowTemplateService.updateTemplate');
      throw error;
    }
  }

  /**
   * Delete workflow template
   */
  public async deleteTemplate(templateId: number): Promise<void> {
    try {
      await this.pnpService.deleteListItem('Workflow Templates', templateId);
    } catch (error) {
      ErrorHandlerService.handle(error as Error, 'WorkflowTemplateService.deleteTemplate');
      throw error;
    }
  }

  /**
   * Get all active templates
   */
  public async getActiveTemplates(): Promise<IWorkflowTemplate[]> {
    try {
      const templates = await this.pnpService.getListItems<any>(
        'Workflow Templates',
        undefined,
        'IsActive eq true',
        'ProcessType asc, TemplateName asc'
      );

      const workflowTemplates: IWorkflowTemplate[] = [];

      for (const template of templates) {
        const taskTemplates = await this.getTaskTemplates(template.TemplateId);
        workflowTemplates.push(this.mapToWorkflowTemplate(template, taskTemplates));
      }

      return workflowTemplates;
    } catch (error) {
      ErrorHandlerService.handle(error as Error, 'WorkflowTemplateService.getActiveTemplates');
      return [];
    }
  }

  /**
   * Get template by ID
   */
  private async getTemplateById(templateId: string): Promise<IWorkflowTemplate | null> {
    try {
      const templates = await this.pnpService.getListItems<any>(
        'Workflow Templates',
        undefined,
        `TemplateId eq '${templateId}'`,
        undefined,
        1
      );

      if (templates.length === 0) {
        return null;
      }

      const taskTemplates = await this.getTaskTemplates(templateId);
      return this.mapToWorkflowTemplate(templates[0], taskTemplates);
    } catch (error) {
      ErrorHandlerService.handle(error as Error, 'WorkflowTemplateService.getTemplateById');
      return null;
    }
  }

  /**
   * Get task templates for a workflow template
   */
  private async getTaskTemplates(workflowTemplateId: string): Promise<IWorkflowTaskTemplate[]> {
    try {
      const taskTemplates = await this.pnpService.getListItems<any>(
        'Workflow Task Templates',
        undefined,
        `WorkflowTemplateId eq '${workflowTemplateId}'`,
        'SequenceOrder asc'
      );

      return taskTemplates.map(tt => ({
        Id: tt.Id,
        taskTemplateId: tt.TaskTemplateId,
        workflowTemplateId: tt.WorkflowTemplateId,
        title: tt.TaskTitle,
        description: tt.TaskDescription,
        taskCategory: tt.TaskCategory,
        priority: tt.TaskPriority,
        sequenceOrder: tt.SequenceOrder,
        daysOffset: tt.DaysOffset,
        estimatedHours: tt.EstimatedHours,
        isRequired: tt.IsRequired,
        dependencies: tt.Dependencies?.split(', ').filter((d: string) => d.trim()),
        assignmentRule: tt.AssignmentRule,
        assigneeRole: tt.AssigneeRole,
        assigneeEmail: tt.AssigneeEmail,
        requiresApproval: tt.RequiresApproval,
        autoComplete: tt.AutoComplete,
        notifyOnAssignment: tt.NotifyOnAssignment,
        notifyBeforeDueDays: tt.NotifyBeforeDueDays,
        instructions: tt.Instructions
      }));
    } catch (error) {
      return [];
    }
  }

  /**
   * Resolve assignee based on assignment rule
   */
  private async resolveAssignee(
    taskTemplate: IWorkflowTaskTemplate,
    overrides?: {
      hrCoordinatorId?: number;
      itCoordinatorId?: number;
      managerId?: number;
      department?: string;
    }
  ): Promise<number | undefined> {
    switch (taskTemplate.assignmentRule) {
      case TaskAssignmentRule.Specific:
        // Would need to look up user by email
        return undefined;

      case TaskAssignmentRule.HRCoordinator:
        return overrides?.hrCoordinatorId;

      case TaskAssignmentRule.ITCoordinator:
        return overrides?.itCoordinatorId;

      case TaskAssignmentRule.Manager:
        return overrides?.managerId;

      case TaskAssignmentRule.Department:
        // Would need to look up department coordinator
        return undefined;

      case TaskAssignmentRule.Employee:
        // Assigned to employee - would be set from process
        return undefined;

      default:
        return undefined;
    }
  }

  /**
   * Map SharePoint list item to WorkflowTemplate
   */
  private mapToWorkflowTemplate(item: any, taskTemplates: IWorkflowTaskTemplate[]): IWorkflowTemplate {
    return {
      Id: item.Id,
      templateId: item.TemplateId,
      templateName: item.TemplateName,
      description: item.Description,
      processType: item.ProcessType,
      isActive: item.IsActive,
      department: item.Department,
      employeeType: item.EmployeeType,
      priority: item.Priority,
      tasks: taskTemplates,
      estimatedDurationDays: item.EstimatedDurationDays,
      createdDate: new Date(item.Created),
      modifiedDate: new Date(item.Modified)
    };
  }

  /**
   * Map SharePoint list item to JMLTask
   */
  private mapToJMLTask(item: any): IJMLTask {
    return {
      Id: item.Id,
      title: item.Title,
      taskDescription: item.JMLTaskDescription,
      processId: item.JMLProcessLookupId,
      employeeId: item.JMLTaskEmployeeLookupId,
      taskCategory: item.JMLTaskCategory,
      taskStatus: item.JMLTaskStatus,
      priority: item.JMLTaskPriority,
      dueDate: item.JMLTaskDueDate ? new Date(item.JMLTaskDueDate) : undefined,
      completedDate: item.JMLTaskCompletedDate ? new Date(item.JMLTaskCompletedDate) : undefined,
      assignedTo: item.JMLTaskAssignedTo,
      estimatedHours: item.JMLTaskEstimatedHours,
      actualHours: item.JMLTaskActualHours,
      sequenceOrder: item.JMLTaskSequence,
      dependencies: item.JMLTaskDependencies,
      blockingReason: item.JMLTaskBlockingReason,
      autoGenerated: item.JMLTaskAutoGenerated,
      templateSource: item.JMLTaskTemplateSource,
      notes: item.JMLTaskNotes
    };
  }
}
